Time (summit),Event,Target,Exposure numbers(s),Exposure Time (secs),Good Spectrum?,Comments
2022-04-05 18:30:00,"Night crew arrives to summit, beginning daily checkout",,,,,
2022-04-05 19:23:00,Beginning afternoon calibrations.,,,,,
2022-04-05 21:03:00,Running prepare for onsky with script queue,,,,,
2022-04-05 22:30:00,"Attempted to run scriptQueue wfs script, but it failed",,,,,"Error in run

b'Traceback (most recent call last):
 File ""/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-3.0.0/lib/python3.8/site-packages/lsst/ts/salobj/base_script.py"", line 589, in do_run
 await self._run_task
 File ""/home/saluser/ts_externalscripts/python/lsst/ts/externalscripts/auxtel/latiss_cwfs_align.py"", line 974, in run
 await self.arun(True)
 File ""/home/saluser/ts_externalscripts/python/lsst/ts/externalscripts/auxtel/latiss_cwfs_align.py"", line 869, in arun
 results = await self.run_cwfs()
 File ""/home/saluser/ts_externalscripts/python/lsst/ts/externalscripts/auxtel/latiss_cwfs_align.py"", line 389, in run_cwfs
 self.intra_exposure, self.extra_exposure = await asyncio.gather(
 File ""/home/saluser/ts_observing_utilities/python/lsst/ts/observing/utilities/auxtel/latiss/getters.py"", line 66, in get_image
 raise TimeoutError(
TimeoutError: Unable to get raw image from butler in 20.0 seconds.'

See OBS-25"
2022-04-05 22:35:00,"Initiated script again, completed successfully.",,,,,
2022-04-05 22:42:00,Determine that this failed due to a dropped image 207 - no butler image,,,,,
2022-04-05 22:52:00,Running acquire and take sequence to absorb pointing offsets,,,,,
2022-04-05 22:54:00,"12 degree twilight, beginning of science time",,,,,
2022-04-05 23:00:00,Running scheduler driven operations,,,,,
2022-04-05 23:30:00,"Relying on Gemini DIMM data for the moment, in the process of troubleshooting Rubin DIMM - See OBS-27",,,,,
2022-04-05 23:43:00,Scheduler went into fault - beginning technical time loss,,,,,"Error on advance target production loop.
Traceback (most recent call last): File ""/opt/lsst/software/stack/miniconda/lib/python3.8/site-packages/aiohttp/connector.py"", line 1154, in _create_direct_connection hosts = await  aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host influxdb-summit-efd.lsst.codes:30828 ssl:default [Name or service not known]"
2022-04-05 23:51:00,"Unable to talk to EFD, and notebook servers have crashed",,,,,
2022-04-06 00:00:00,*Lost all CSCs on the k8 clusters*,,,,,
2022-04-06 00:11:00,"*After cluster was re-started, recovered ATCS and CSCs*",,,,,
2022-04-06 00:18:00,"Resumed scheduler operations, starting with cwfs - end technical time loss",,,,,
2022-04-06 00:20:00,DIMM begins working after some trouble.,,,,,
2022-04-06 00:24:00,"We did not enable ataos corrections, scheduler went into fault - educational time",,,,,
2022-04-06 00:39:00,Running a new focus script separate from scheduler - establishing new baseline,,,,,
2022-04-06 00:43:00,Script failed due to a second bright star in the field - ts_external_scripts was on the wrong branch,,,,,
2022-04-06 00:44:00,Re-running script on a new target - end of educational time,,,,,
2022-04-06 00:49:00,Resuming scheduler-driven operations,,,,,
2022-04-06 00:56:00,Interrupt scheduler-driven observations to go for engineering,,,,,
2022-04-06 01:19:00,Resume scheduler driving operations after environment troubles,,,,,
2022-04-06 02:25:00,"ATPtg went into fault, nasmyth 2 max velocity error exceeded - technical fault",,,,,DM-30709
2022-04-06 02:28:00,Recovered,,,,,
2022-04-06 03:02:00,"Nasmyth 2 max velocity exceeded, causing a ATPtg fault. Recovered CSCs.",,,,,
2022-04-06 03:05:00,"Going to rotate nasmyth with the EUI from 132 â†’ 20 to try and ""kick the error out."" Be gone, Beezulbub!",,,,,
2022-04-06 03:10:00,"After going in through the EUI and trying to force the nasmyth, the telescope does not respond to slew/pointing commands.",,,,,
2022-04-06 03:20:00,Sending ATPTg and ATMCS CSCs to standby and back to enabled.,,,,,
2022-04-06 03:25:00,Telescope not receiving target commands.,,,,,Exception image
2022-04-06 03:38:00,"Sending the pointing to offline, and then back online. Able to slew.",,,,,
2022-04-06 03:40:00,Beginning some engineering tasks.,,,,,
2022-04-06 03:45:00,Eng#1_Donut_Pairs Eng#1_Donut_Pairs.pdf,,,(449 to 521),,
2022-04-06 03:50:00,Eng#3_Parabolic Focus Sweep  Eng#3_Parabolic_Focus_Sequence.pdf,,,"(523, 531)",,
2022-04-06 03:55:00,Eng#2_PSF_Ellipticity Eng#2_PSF_Ellipticipy.pdf,,,"(536, 601) are these actually expsure numbers?",,Link to sequence list
2022-04-06 05:21:00,Going to go back to scheduler.,,,,,
2022-04-06 07:35:00,"Notice that scriptQueue is hung up on wfs calculation, possibly due to another bright target in the field.",,,,,
2022-04-06 07:41:00,"Kill the step, continue with imaging.",,,,,
2022-04-06 07:43:00,Load a separate cwfs to catch a focus and continue with survey.,,,,,
2022-04-06 09:02:00,Scheduler goes into fault due to not having another target - calling the night.,,,,,
2022-04-06 09:04:00,Beginning of nautical twilight. Running shutdown script.,,,,,
2022-04-06 09:10:00,Night crew departing summit.,,,,,
